INSTALL_OPS = -o www-data -g www-data
CGI_PATH = /usr/lib/cgi-bin/backup
LDEFINES = -DBACKUP_DIR='"/scsi/www/backup_system"'\
-DCGI_DIR='"https://193.168.0.5/cgi-bin/backup"'\
-DHOME='"https://193.168.0.5/backup.d"'

install:
	$(INSTALL) $(INSTALL_OPS) add_file $(CGI_PATH)/add_file.cgi
	$(INSTALL) $(INSTALL_OPS) logout_user $(CGI_PATH)/logout_user.cgi
	$(INSTALL) $(INSTALL_OPS) lookup_user $(CGI_PATH)/lookup_user.cgi
	$(INSTALL) $(INSTALL_OPS) delete_files $(CGI_PATH)/delete_files.cgi
	$(INSTALL) $(INSTALL_OPS) display_files $(CGI_PATH)/display_files.cgi
	$(INSTALL) $(INSTALL_OPS) upload_script.pl $(CGI_PATH)
